Fixed one warning and two errors reported by VC 6.0.
BitKeeper/etc/ignore:
  Added ndb/tools/ndb_restore to the ignore list
sql/item.cc:
  Fixed VC 6.0 warning:
  mysql-5.0.2-alpha\sql\item.cpp(1729) : warning C4715: 'resolve_ref_in_select_and_group' : not all control paths return a value
sql/opt_range.cc:
  Fixed VC 6.0 errors:
  ERROR # 4: mysql-5.0.2-alpha\sql\opt_range.cpp(8070) : error C2664: 'key_cmp' : cannot convert parameter 2 from 'char *' to 'const unsigned char *'
          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
  
  ERROR # 5: mysql-5.0.2-alpha\sql\opt_range.cpp(8196) : error C2664: 'key_cmp' : cannot convert parameter 2 from 'char *' to 'const unsigned char *'
          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast